### ISSUE TITLE
last update not working

### ISSUE THREAD

**Issue by toshibochan** [solowalker27/homebridge-onkyo#8]
I just update to the latest update and now Homebridge not starting.

Error: The requested platform 'Onkyo' was not registered by any plugin.

**Comment by toshibochan** [comment]
now is not platform anymore?

**Comment by toshibochan** [comment]
I change platform to accessories and now give me this error:

[9/3/2019, 6:27:14 PM] TypeError: Cannot read property 'addLinkedService' of undefined
    at OnkyoAccessory.createVolumeDimmer (/usr/lib/node_modules/homebridge-onkyo/index.js:870:11)
    at OnkyoAccessory.createTvService (/usr/lib/node_modules/homebridge-onkyo/index.js:904:9)
    at OnkyoAccessory.setUp (/usr/lib/node_modules/homebridge-onkyo/index.js:136:26)
    at new OnkyoAccessory (/usr/lib/node_modules/homebridge-onkyo/index.js:123:8)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:308:29)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[9/3/2019, 6:27:14 PM] TypeError: Cannot read property 'getCharacteristic' of undefined
    at OnkyoAccessory.getPowerState (/usr/lib/node_modules/homebridge-onkyo/index.js:485:18)
    at pollingtoevent.longpolling (/usr/lib/node_modules/homebridge-onkyo/index.js:224:10)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-onkyo/node_modules/polling-to-event/index.js:77:5)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[9/3/2019, 6:27:15 PM] TypeError: Cannot read property 'getCharacteristic' of undefined
    at OnkyoAccessory.eventInput (/usr/lib/node_modules/homebridge-onkyo/index.js:343:19)
    at EventEmitter.emit (events.js:198:13)
    at Socket.<anonymous> (/usr/lib/node_modules/homebridge-onkyo/node_modules/eiscp/eiscp.js:393:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by toshibochan** [comment]
"accessories": [{
                "accessory": "Onkyo",
                "model": "TX-NR609",
                "ip_address": "10.0.1.14",
                "poll_status_interval": "30",
                "name": "Receiver",
                "inputs": {
                        "dvd": "APTV 4K",
                        "video2": "APTV JP",
                        "video3": "Fire TV"
                },
                "volume_dimmer": true,
                "switch_service": false,
                "filter_inputs": true
        }, {

**Comment by toshibochan** [comment]
[9/3/2019, 6:48:43 PM] TypeError: Cannot read property 'addLinkedService' of undefined
    at OnkyoAccessory.createVolumeDimmer (/usr/lib/node_modules/homebridge-onkyo/index.js:870:11)
    at OnkyoAccessory.createTvService (/usr/lib/node_modules/homebridge-onkyo/index.js:904:9)
    at OnkyoAccessory.setUp (/usr/lib/node_modules/homebridge-onkyo/index.js:136:26)
    at new OnkyoAccessory (/usr/lib/node_modules/homebridge-onkyo/index.js:123:8)
    at Server._loadAccessories (/usr/lib/node_modules/homebridge/lib/server.js:308:29)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:91:38)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[9/3/2019, 6:48:43 PM] TypeError: Cannot read property 'getCharacteristic' of undefined
    at OnkyoAccessory.getPowerState (/usr/lib/node_modules/homebridge-onkyo/index.js:485:18)
    at pollingtoevent.longpolling (/usr/lib/node_modules/homebridge-onkyo/index.js:224:10)
    at Timeout._onTimeout (/usr/lib/node_modules/homebridge-onkyo/node_modules/polling-to-event/index.js:77:5)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[9/3/2019, 6:48:43 PM] Got SIGTERM, shutting down Homebridge...
[9/3/2019, 6:48:43 PM] [Receiver] eventError: ERROR (send_not_connected) Not connected, can't send data: "PWRQSTN"
[9/3/2019, 6:48:43 PM] [Receiver] eventError: ERROR (send_not_connected) Not connected, can't send data: "SLIQSTN"
[9/3/2019, 6:48:43 PM] [Receiver] getInputState - INPUT QRY: ERROR - current i_state: 1
[9/3/2019, 6:48:43 PM] [Receiver] eventError: ERROR (send_not_connected) Not connected, can't send data: "AMTQSTN"
[9/3/2019, 6:48:43 PM] [Receiver] eventError: ERROR (send_not_connected) Not connected, can't send data: "MVLQSTN"
[9/3/2019, 6:48:46 PM] [Receiver] eventError: ERROR (server_error) Server error on 10.0.0.14:60128 - Error: connect EHOSTUNREACH 10.0.0.14:60128

**Comment by toshibochan** [comment]
How I can download previous version?

**Comment by Goldsucher** [comment]
> I just update to the latest update and now Homebridge not starting.
> 
> Error: The requested platform 'Onkyo' was not registered by any plugin.

I get the same error

**Comment by toshibochan** [comment]
I was able to downgrade by going to platform version and copy index file and replace.
![25391643-9703-45FC-AC7E-7EB870FC5E5B](https://user-images.githubusercontent.com/15816913/64479452-145fb300-d16c-11e9-8302-209ac5a077e8.jpeg)

**Comment by solowalker27** [comment]
Sorry, I'm not getting notifications for issues on this project. Not sure why.

And I also apologize for not testing the latest changes more thoroughly. I've been doing a refactor and keep going back and forth with how to do what I'm doing.

Yes, I did change it back to being an accessory and not a platform, but that was for creating a PR for merging back into Todd's fork. Since he's not maintaining his anymore, I'm considering just publishing this to npm as a different package and not worrying about compatibility with Todd's.

I'm doing more work on this today and hopefully will commit the changes soon. I'll probably move it back to a platform. I'll look into this error you're reporting, too.

**Comment by solowalker27** [comment]
Pushed version 0.7.2. This goes back to a Platform. Should fix the volume dimmer, too. Please try it out and see if it solves your issues.
